baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Mostafa's Blog"

#theme = 'hugo-ink'
theme = 'simplist'

paginate = 10
copyright = "All contents under <a href=\"https://www.gnu.org/licenses/fdl-1.3.html\">GNU FDL</a>"

#googleAnalytics = "G-LDWY8DT7E9"
googleTagManager = "G-LDWY8DT7E9"

[params]
	subtitle = "A software engineer with many non-technical hobbies like flying, cooking and gardening!"
	mode = "auto" # "dark" or "auto"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mirmousaviii"


[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "http://ir.linkedin.com/in/mirmousavi/en"


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/m_like_martini"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/mirmousaviii/"


[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"


# Nav.

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
