title = "Mostafa Mirmousavi"
baseURL = 'http://mirmousavi.com/'

theme = 'mostafa-hugo-theme'

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "G-LDWY8DT7E9"

[params]
    # Custom CSS / JS modules that will be imported by the template.
    # Files are relative to the static/ directory or a URL.
    # Files are imported in the order they appear here, after
    # theme.css and theme.js, respectively.
#    css_modules = ["..", "//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css"]
#    js_modules = ["..", "//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js", "init-cookieconsent.js"]
    css_modules = []
    js_modules = []

    # Description and meta data for the search engines
    author = "Mostafa Mirmousavi"
    description = "A software engineer with many non-technical hobbies like flying, cooking and gardening!"
    keywords = "mostafa,mirmousavi,coderconf,persianlug"

    subtitle = "A software engineer with many non-technical hobbies like flying, cooking and gardening!"

    #avatarEmail = "mirmousavi.m@gmail.com"

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = "avatar.jpg"

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # How many articles should be displayed at once?
    paginate = 10

    # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

    # always display the top navigation (with pages and search) on non-mobile screens
    #permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    #stickyNav = true

    # show a language chooser in the header
    #showHeaderLanguageChooser = false


# Color
#    pageBackgroundColor= "#f1f1f1"
#    baseColor = "#25242A"
#    specialColor = "#25242A"
#    highlightColor = "#0594cb"

#    pageBackgroundColor= "#111827"
#    baseColor = "#1F2937"
#    specialColor = "#25242A"
#    highlightColor = "#0594cb"
#    textColor = "#000"
#
#    navBackgroundColor = "$special-color"
#    navTextColor = "#fff"
#
#    headerTextColor = "#F9F4DA"
#    logoColor = "darken($page-background-color, 1)"
#    bubbleColor =  "#fff"
#    bubbleBackgroundColor = "#ccc"
#    bubbleHoverColor = "$highlight-color"
#
#    articleBackgroundColor = "#1F2937"
#    metaTextColor = "#fff"
#    metaBorderColor = "#eee"
#    continueReadingHoverColor = "$meta-text-color"
#
#    footerBorderColor = "#eee"
#    footerBackgroundColor = "$base-color"

# Content configuration
    # Enable an optional pinned page to display at the top of the index
    #pinnedPost = "/quote/routine/"
    # Set to true to pin only to the first page, false to all pages
    #pinOnlyToFirstPage = true

    # enable highlight.js for syntax highlighting or (if set to false) use
    # the hugo built-in chroma highlighter
    #enableHighlightJs = true

    # enable automatic localization of the article's PublishedDate with momentjs
    #enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    #dateFormat = "2023-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

# Footer configuration
    #showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 5

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 10

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
    { name = "GitHub", link = "https://github.com/mirmousaviii", icon = "fab fa-github"},
    { name = "Linkedin", link = "http://linkedin.com/in/mirmousavi/en", icon = "fab fa-linkedin" },
    { name = "Instagram", link = "https://www.instagram.com/mirmousaviii/", icon = "fab fa-instagram" },
    { name = "Twitter / X", link = "https://twitter.com/mirmousaviii", icon = "fab fa-twitter" },
#    { name = "RSS", link = "/index.xml", icon = "fa fa-rss" },
    ]

otherLinks = [
    { name = "Persian LUG", link = "https://persianlug.com/"},
    { name = "CoderConf", link = "https://coderconf.org/"},
]

    # show an archive link in the footer
    #showArchive = true

    # archive grouping: "2006" by year, "2006-01" by month
    #archiveDateGrouping = "2006-01"

    # credits line configuration
#    copyrightBy = "by Mostafa Mirmousavi"
#    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
#    copyrightYearOverride = "2023"
#    copyrightUrl = "https://mirmousavi.com"
#    creditsText = "Powered by Hugo ♥"
#    creditsUrl = "https://gohugo.io/"


# customize your available languages for your multi-lingual site
# or delete one of the [Languages.xx] blocks to use the theme with only one supported language
#[Languages]
#    [Languages.en]
#        weight = 1
#        languageCode = 'en-US'
#        languageDirection = 'ltr'
#        languageName = 'English'
#        title = "Mostafa's Blog"
#        subtitle = "A software engineer with many non-technical hobbies like flying, cooking and gardening!"
#        [languages.en.params]
#            subtitle = "A software engineer with many non-technical hobbies like flying, cooking and gardening!"
#    [Languages.fa]
#        weight = 2
#        languageCode = 'fa-IR'
#        languageDirection = 'rtl'
#        languageName = 'Persian'
#        title = "مصطفی میرموسوی"
#        subtitle = "یک برنامه‌نویس با کلی سرگرمی غیر‌فنی"
#        [languages.fa.params]
#            subtitle = "یک برنامه‌نویس با کلی سرگرمی غیر‌فنی"

[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = false

    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 2

# do NOT change anything below
[taxonomies]
    author   = "author"
    tag      = "tags"
    category = "categories"
    series   = "series"

[outputs]
    home = [ "HTML", "JSON", "RSS" ]
    page = [ "HTML" ]